//Dependancies
  const tester = require(require("path").join(__dirname, "..", "tester"))

//Tests
  ;[
    {
      filename:"[BlurayDesuYo] Shingeki no Kyojin (Season 3) - Batch (BD 1920x1080 10bit FLAC)",
      subber:"BlurayDesuYo",
      name:"Shingeki no Kyojin",
      season:"3",
      meta:"batch",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit flac",
    },
    {
      filename:"[Leopard-Raws] Shingeki no Kyojin Season 3 Part.2 - 09 END RAW (NHKG 1280x720 x264 AAC).mp4",
      subber:"Leopard-Raws",
      name:"Shingeki no Kyojin",
      season:"3",
      episode:"9",
      part:"2",
      source:"raw",
      resolution:"720p",
      codecs:"aac x264",
      extension:"mp4",
    },
    {
      filename:"[ZetaRebel] Ghost in the Shell (1995) (BD x264 1080p 8-bit FLAC)",
      subber:"ZetaRebel",
      name:"Ghost in the Shell (1995)",
      source:"bluray",
      codecs:"8bit flac x264",
      resolution:"1080p",
    },
    {
      filename:"[DragsterPS] Ghost in the Shell - SAC_2045 S01 [1080p] [Japanese Audio] [Multi-Subs]",
      subber:"DragsterPS",
      name:"Ghost in the Shell - SAC_2045",
      season:"1",
      resolution:"1080p",
      audio:"jp",
      subtitles:"multi",
    },
    {
      filename:"[Team246] Ghost in the shell Stand alone complex S01 E10-E15 [BDREMUX 1080P MULTi DTSHDMA 5.1][VOSTFR]",
      subber:"Team246",
      name:"Ghost in the shell Stand alone complex",
      season:"1",
      episode:"10-15",
      resolution:"1080p",
      audio:"multi vo",
      subtitles:"fr",
      source:"bluray",
      codecs:"audio_5_1 dts_hdma",
      meta:"remux",
    },
    {
      filename:"[PuyaSubs!] Psycho-Pass 3 - First Inspector - 03 [1080p][1B7B0133].mkv",
      subber:"PuyaSubs!",
      name:"Psycho-Pass 3 - First Inspector",
      episode: "3",
      resolution:"1080p",
      hash:"1B7B0133",
      extension:"mkv",
    },
    {
      filename:"[Lilith-Raws] 心靈判官 / Psycho-Pass Sinners of the System Case.3 [Baha][WEB-DL][1080p][AVC AAC][CHT][MKV]",
      subber:"Lilith-Raws",
      name:"心靈判官 / Psycho-Pass Sinners of the System Case 3",
      source:"webdl",
      resolution:"1080p",
      codecs:"aac avc",
      extension:"mkv",
    },
    {
      filename:"[U3-Web] PSYCHO-PASS 3 - FIRST INSPECTOR (2020) [Movie][AMZN WEB-DL(v) 1080p AVC AAC DDP SRT][Multi-Subs] (PSYCHO-PASS サイコパス / 心靈判官 / 心理測量者)",
      subber:"U3-Web",
      name:"PSYCHO-PASS 3 - FIRST INSPECTOR (2020) (PSYCHO-PASS サイコパス / 心靈判官 / 心理測量者)",
      distributor:"amazon",
      resolution:"1080p",
      subtitles:"multi",
      codecs:"aac avc",
      source:"webdl",
    },
    {
      filename:"[RLSP] One Piece - Dressrosa 629-746",
      subber:"RLSP",
      name:"One Piece - Dressrosa",
      episode:"629-746",
    },
    {
      filename:"[KaiDubs] One Piece - 575-587 [720p] [English Dub] [CC] [AMZN-DL]",
      subber:"KaiDubs",
      name:"One Piece",
      episode:"575-587",
      resolution:"720p",
      audio:"en",
      distributor:"amazon comedy_central"
    },
    {
      filename:"One Piece Season 10 Voyage 1 (Eps. 575-587) (Dual Audio 1080p JP BD Remuxes)",
      name:"One Piece Voyage 1",
      season:"10",
      episode:"575-587",
      resolution:"1080p",
      audio:"jp",
      codecs:"dual_audio",
      source:"bluray",
      meta:"remux",
    },
    {
      filename:"One piece 590 X Toriko X Dragon Ball Z Crossover [animestorrent.com][Legendado][PT-BR]",
      name:"One piece 590 X Toriko X Dragon Ball Z Crossover",
      website:"animestorrent.com",
      source:"bluray",
      subber:"Legendado",
    },
    {
      filename:"[Kaerizaki-Fansub]_One-Piece_Stampede_Film_14_[VERSION-LIGHT][VOSTFR][BLU-RAY][FHD_1920x1080].mp4",
      name:"One-Piece Stampede Film 14",
      subber:"Kaerizaki-Fansub",
      audio:"vo",
      subtitles:"fr",
      source:"bluray",
      resolution:"1080p",
      extension:"mp4",
    },
    {
      filename:"[Cervoz] Serial Experiments Lain [1080p][MULTI][VF - VOSTFR][10Bits]",
      subber:"Cervoz",
      name:"Serial Experiments Lain",
      resolution:"1080p",
      audio:"fr multi vo",
      subtitles:"fr",
      codecs:"10bit",
    },
    {
      filename:"[JpU - No oficial] Serial Experiments Lain",
      subber:"JpU - No oficial",
      name:"Serial Experiments Lain",
    },
    {
      filename:"Serial Experiments Lain (1998) 1080p.H264.Ac3.Ita.Flac.Jap.Eng.Sub.Ita.Eng [v2] [21GB] [stress]",
      subber:"stress",
      name:"Serial Experiments Lain (1998)",
      resolution:"1080p",
      codecs:"ac3 flac h264",
      audio:"en ita jp",
      subtitles:"en ita",
      meta:"v2",
    },
    {
      filename:"[Reaktor] From the New World - Shinsekai Yori [1080p][BD][x265][10-bit][Dual-Audio]",
      subber:"Reaktor",
      name:"From the New World - Shinsekai Yori",
      resolution:"1080p",
      source:"bluray",
      codecs:"10bit dual_audio x265",
    },
    {
      filename:"[AnimeRG] Shinsekai Yori (From the New World) [01-25] [Complete] [1080p] [HEVC] [TheBiscuitMan]",
      subber:"AnimeRG",
      name:"Shinsekai Yori (From the New World)",
      episode:"1-25",
      resolution:"1080p",
      codecs:"hevc",
      meta:"complete",
    },
    {
      filename:"[hoseki]_Shinsekai_Yori_-_14-16_(BD_1080p_FLAC)",
      subber:"hoseki",
      name:"Shinsekai Yori",
      episode:"14-16",
      source:"bluray",
      resolution:"1080p",
      codecs:"flac",
    },
    {
      filename:"[T.H.X&A.I.R.nesSub][Shinsekai_Yori][BDRIP][Vol.1-9全][1920x1080_10bpp][AVC_FLAC][MKV]",
      subber:"T.H.X&A.I.R.nesSub",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit avc flac",
      extension:"mkv",
      name:"Shinsekai Yori",
      episode:"1-9",
    },
    {
      filename:"[RnF] Shinsekai Yori - 24 - BD - Vostfr.mp4",
      subber:"RnF",
      name:"Shinsekai Yori",
      episode:"24",
      source:"bluray",
      audio:"vo",
      subtitles:"fr",
      extension:"mp4",
    },
    {
      filename:"[AT] [Moshi Moshi] Fullmetal Alchemist Brotherhood - Star Of Milos [BD 720p] [01A4B7E9][Legendado][PT_BR][AnimesTorrent]",
      name:"Fullmetal Alchemist Brotherhood - Star Of Milos",
      hash:"01A4B7E9",
      source:"bluray",
      resolution:"720p",
      subber:"Moshi Moshi",
    },
    {
      filename:"[BDRip1080p.x264.AC3.ITA.ENG.JAP.].Fullmetal.Alchemist.Brotherhood + OAV Bluray RIP",
      name:"Fullmetal Alchemist Brotherhood + OAV",
      audio: "en ita jp",
      source:"bluray",
      resolution:"1080p",
      codecs:"ac3 x264",
    },
    {
      filename:"[UQW] Fullmetal Alchemist: Brotherhood [BD 1080p AVC-YUV420P10 FLAC]",
      subber:"UQW",
      name:"Fullmetal Alchemist: Brotherhood",
      source:"bluray",
      resolution:"1080p",
      codecs:"avc flac",
    },
    {
      filename:"Fullmetal Alchemist Brotherhood + OVAs + Specials [ShadyCrab 1080p 8bit AAC] [Dual Audio]",
      name:"Fullmetal Alchemist Brotherhood + OVAs + Specials",
      resolution:"1080p",
      codecs:"8bit aac dual_audio",
      subber:"ShadyCrab",
    },
    {
      filename:"[Xspitfire911] Fullmetal Alchemist Brotherhood + OAV BDRIP 1080p X265 10bit Vostfr",
      subber:"Xspitfire911",
      name:"Fullmetal Alchemist Brotherhood + OAV",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit x265",
      audio:"vo",
      subtitles:"fr",
    },
    {
      filename:"Bleach Movie 01 - Memories of Nobody [H264 1080p DTS Ita Eng Jap SUB Ita Eng] [Rady]",
      name:"Bleach Movie - Memories of Nobody",
      codecs:"dts h264",
      resolution:"1080p",
      audio:"en ita jp",
      subtitles:"en ita",
      subber:"Rady",
      movie:"1",
    },
    {
      filename:"[2ndfire] Spirited Away / Sen to Chihiro no Kamikakushi [BD,1080p,AV1,10bit][36C04BDB]",
      subber:"2ndfire",
      hash:"36C04BDB",
      name:"Spirited Away / Sen to Chihiro no Kamikakushi",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit av1",
    },
    {
      filename:"[AnimeRG] Spirited Away (2001) (Sen to Chihiro no Kamikakushi) [720p BD 10bit] [Dual Audio] [Multi-Language Subtitles] [JRR] [Studio Ghibli].mkv",
      subber:"AnimeRG",
      name:"Spirited Away (2001) (Sen to Chihiro no Kamikakushi)",
      resolution:"720p",
      source:"bluray",
      codecs:"10bit dual_audio",
      subtitles:"multi",
      extension:"mkv",
    },
    {
      filename:"Spirited Away 1080p Dubbed English",
      name:"Spirited Away",
      resolution:"1080p",
      audio:"en",
    },
    {
      filename:"[千与千寻].Spirited.Away.2001.BluRay.1080p.DTS-HD.MA.6.1.x265.10bit-BeiTai&NetFriend",
      name:"千与千寻 Spirited Away 2001",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit dts_hdma x265",
      subber:"BeiTai&NetFriend",
    },
    {
      filename:"[Dragonier] Sen to Chihiro no Kamikakushi - Spirited Away [1080p][6.1ch - FLAC][86FFE17E].mkv",
      name:"Sen to Chihiro no Kamikakushi - Spirited Away",
      subber:"Dragonier",
      resolution:"1080p",
      hash:"86FFE17E",
      extension:"mkv",
      codecs:"flac",
    },
    {
      filename:"[matheousse] Death Note MULTi VF/VOSTFR (BD 1080p AAC)",
      subber:"matheousse",
      name:"Death Note",
      audio:"fr multi vo",
      subtitles:"fr",
      source:"bluray",
      resolution:"1080p",
      codecs:"aac",
    },
    {
      filename:"[AnimeRG] Death Note Complete [01-37] [Dual Audio] [480p BD] [10bit] [Multi-Subs] [JRR]",
      subber:"AnimeRG",
      name:"Death Note",
      episode:"1-37",
      codecs:"10bit dual_audio",
      subtitles:"multi",
      source:"bluray",
      resolution:"480p",
      meta:"complete"
    },
    {
      filename:"[SOFCJ-Raws] Death Note (BDRip 1920x1080 x264 10bit VFR FLAC)",
      subber:"SOFCJ-Raws",
      name:"Death Note",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit flac x264",
      audio:"fr",
    },
    {
      filename:"Death Note 1-37 [480p] [EN SUB]",
      name:"Death Note",
      resolution:"480p",
      episode:"1-37",
      subtitles:"en",
    }
  ].forEach(tester)
