//Dependancies
  const {default:ATNP} = require(require("path").join(__dirname, "../..", "dist/ATNP"))
  console.debug = () => null

//Tests
  ;[
    {
      filename:"[BlurayDesuYo] Shingeki no Kyojin (Season 3) - Batch (BD 1920x1080 10bit FLAC)",
      subber:"BlurayDesuYo",
      name:"Shingeki no Kyojin",
      season:"3",
      meta:"batch",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit flac",
    },
    {
      filename:"[Leopard-Raws] Shingeki no Kyojin Season 3 Part.2 - 09 END RAW (NHKG 1280x720 x264 AAC).mp4",
      subber:"Leopard-Raws",
      name:"Shingeki no Kyojin",
      season:"3",
      episode:"9",
      part:"2",
      source:"raw",
      resolution:"720p",
      codecs:"aac x264",
      extension:"mp4",
    },
    {
      filename:"[ZetaRebel] Ghost in the Shell (1995) (BD x264 1080p 8-bit FLAC)",
      subber:"ZetaRebel",
      name:"Ghost in the Shell (1995)",
      source:"bluray",
      codecs:"8bit flac x264",
      resolution:"1080p",
    },
    {
      filename:"[DragsterPS] Ghost in the Shell - SAC_2045 S01 [1080p] [Japanese Audio] [Multi-Subs]",
      subber:"DragsterPS",
      name:"Ghost in the Shell SAC_2045",
      season:"1",
      resolution:"1080p",
      audio:"jp",
      subtitles:"multi",
    },
    {
      filename:"[Team246] Ghost in the shell Stand alone complex S01 E10-E15 [BDREMUX 1080P MULTi DTSHDMA 5.1][VOSTFR]",
      subber:"Team246",
      name:"Ghost in the shell Stand alone complex",
      season:"1",
      episode:"10-15",
      resolution:"1080p",
      audio:"multi vo",
      subtitles:"fr",
      source:"bluray",
      codecs:"audio_5_1 dts_hdma",
      meta:"remux",
    },
    {
      filename:"[PuyaSubs!] Psycho-Pass 3 - First Inspector - 03 [1080p][1B7B0133].mkv",
      subber:"PuyaSubs!",
      name:"Psycho-Pass 3 First Inspector",
      episode: "3",
      resolution:"1080p",
      hash:"1B7B0133",
      extension:"mkv",
    },
    {
      filename:"[KaiDubs] One Piece - 575-587 [720p] [English Dub] [CC] [AMZN-DL]",
      subber:"KaiDubs",
      name:"One Piece",
      episode:"575-587",
      resolution:"720p",
      audio:"en",
      distributor:"amazon comedy_central"
    },
    {
      filename:"One piece 590 X Toriko X Dragon Ball Z Crossover [animestorrent.com][Legendado][PT-BR]",
      name:"One piece 590 X Toriko X Dragon Ball Z Crossover",
      website:"animestorrent.com",
      source:"bluray",
      subber:"Legendado",
    },
    {
      filename:"[Cervoz] Serial Experiments Lain [1080p][MULTI][VF - VOSTFR][10Bits]",
      subber:"Cervoz",
      name:"Serial Experiments Lain",
      resolution:"1080p",
      audio:"fr multi vo",
      subtitles:"fr",
      codecs:"10bit",
    },
    {
      filename:"Serial Experiments Lain (1998) 1080p.H264.Ac3.Ita.Flac.Jap.Eng.Sub.Ita.Eng [v2] [21GB] [stress]",
      subber:"[stress]",
      name:"Serial Experiments Lain (1998)",
      resolution:"1080p",
      codecs:"ac3 flac h264",
      audio:"en ita jp",
      subtitles:"en ita"
    },
    {
      filename:"[Reaktor] From the New World - Shinsekai Yori [1080p][BD][x265][10-bit][Dual-Audio]",
      subber:"Reaktor",
      name:"From the New World Shinsekai Yori",
      resolution:"1080p",
      source:"bluray",
      codecs:"10bit dual_audio x265",
    },
    {
      filename:"[AnimeRG] Shinsekai Yori (From the New World) [01-25] [Complete] [1080p] [HEVC] [TheBiscuitMan]",
      subber:"AnimeRG",
      name:"Shinsekai Yori (From the New World)",
      episode:"1-25",
      resolution:"1080p",
      codecs:"hevc",
      meta:"complete",
    },
    {
      filename:"[T.H.X&A.I.R.nesSub][Shinsekai_Yori][BDRIP][Vol.1-9全][1920x1080_10bpp][AVC_FLAC][MKV]",
      subber:"T.H.X&A.I.R.nesSub",
      source:"bluray",
      resolution:"1080p",
      codecs:"10bit avc flac",
      extension:"mkv",
      name:"Shinsekai_Yori",
      part:"1-9",
    }
  ].forEach(testable => test(testable.filename, () => expect(ATNP.parse(testable.filename)).toEqual(testable)))

/*
 
  ,
  "[Team246] Ghost in the Shell Arise Border 5 [BDREMUX 1080P MULTi VO-VF DTSHDMA] [VOSTFR]",
  "[Commie] Ghost in the Shell SAC_2045 - 03 [4027CD5B].mkv",
  "[DragsterPS] Ghost in the Shell - SAC_2045 S01 [1080p] [Japanese Audio] [Multi-Subs]",
  "[DragsterPS] Ghost in the Shell - SAC_2045 S01 [720p] [HEVC] [Japanese Audio] [Multi-Subs]",
  "Ghost in the Shell - SAC_2045 - Season 1 S01 - 2020 1080p Japanese Audio Multi-Sub NF WEBRip AAC5.1 x264-Rapta",
  "[PuyaSubs!] Psycho-Pass 3 - First Inspector - 03 [1080p][1B7B0133].mkv",
  "[Lilith-Raws] 心靈判官 / Psycho-Pass Sinners of the System Case.3 [Baha][WEB-DL][1080p][AVC AAC][CHT][MKV]",
  "[HorribleSubs] PSYCHO-PASS 3 - First Inspector - 03 [720p].mkv",
  "[U3-Web] PSYCHO-PASS 3 - FIRST INSPECTOR (2020) [Movie][AMZN WEB-DL(v) 1080p AVC AAC DDP SRT][Multi-Subs] (PSYCHO-PASS サイコパス / 心靈判官 / 心理測量者)",
  "[Judas] Psycho-Pass - First Inspector (Movie) [1080p][HEVC x265 10bit][Multi-Subs]",
  "[Erai-raws] Psycho-Pass 3 - First Inspector [720p HEVC][Multiple Subtitle]",
  "[Sunshine] Psycho-Pass 3 - 02 [DD30074B].mkv",
  "[YnK] Psycho-Pass꞉ Sinners of the System Case.1 [BD 720p] [E0A6657B]",
  "[桜都字幕组][心理测量者 3/PSYCHO-PASS心灵判官 3/Psycho-Pass 3][07][GB][1080P]",
  "One Piece Season 10 Voyage 1 (Eps. 575-587) (Dual Audio 1080p JP BD Remuxes)",
  "One piece 590 X Toriko X Dragon Ball Z Crossover [animestorrent.com][Legendado][PT-BR]",
  
  "[SachaOPD] One Piece Deluxe (Fan-Kai) Whole Cake Film 4 - Mégot [V2] (720p AAC VOSTFR)",
  "[Kaerizaki-Fansub]_One-Piece_Stampede_Film_14_[VERSION-LIGHT][VOSTFR][BLU-RAY][FHD_1920x1080].mp4",
  "[TC] [SoM] Kyutai Panic Adventure! [Dragon Ball Z] [One Piece] [Astro Boy] [CAM Rip]",
  "[RLSP] One Piece - Dressrosa 629-746",
  "[RLSP] One Piece - Silver Mine 747-750",
  "[Cleo] Shinsekai yori | From the New World [Dual Audio 10bit BD720p][HEVC-x265]",
  "",
  "[Hayaku] Shinsekai Yori EP 3 [Multi Subs]",
  "[JasinChen][来自新世界][新世界より][Shinsekai Yori][BDRIP 1080p][HEVC h265][Hi10P FLAC]",
  "[AnimeRG] Shinsekai Yori (From the New World) [01-25] [Complete] [1080p] [HEVC] [TheBiscuitMan]",
  "[JacobSwaggedUp] Shinsekai Yori | From the New World (BD 1280x720) [MP4 Batch]",
  "[T.H.X&A.I.R.nesSub][Shinsekai_Yori][BDRIP][Vol.1-9全][1920x1080_10bpp][AVC_FLAC][MKV]",
  "[hoseki]_Shinsekai_Yori_-_14-16_(BD_1080p_FLAC)",
  "[UTW+5] Shinsekai Yori 17-25 + ED2 Patches.7z",
  "[RnF] Shinsekai Yori - 24 - BD - Vostfr.mp4",
  "Serial Experiments Lain (BDRip 1520x1080p x265 HEVC FLACx2 2.0x2)(Dual Audio)[sxales]",
  "Serial Experiments Lain (1998) 1080p.H264.Ac3.Ita.Flac.Jap.Eng.Sub.Ita.Eng [v2] [21GB] [stress]",
  "Serial Experiments Lain Collection 20191206 By Icetric",
  "Serial Experiments Lain (1998) [dual audio] [720p]",
  "[bonkai77] Serial Experiments Lain [1080p] [DUAL-AUDIO] [x265] [HEVC] [AAC] [10bit]",
  "[AnimeRG] Serial Experiments Lain - 2 [960X720] [English Sub] [Web-DL] [Pseudo-ReleaseBitch].mkv",
  "[JpU - No oficial] Serial Experiments Lain",
  "",
  */